sonar.projectKey=jamesleonardgrijalbabolanos_fraude-detection
sonar.organization=jamesleonardgrijalbabolanos
sonar.qualitygate.wait=true

# Excluir el frontend del análisis
sonar.exclusions=frontend/**

# Fuentes del backend
sonar.sources=src/main/java
sonar.tests=src/test/java

# Reporte de cobertura JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Excluir clases que no necesitan cobertura
sonar.coverage.exclusions=**/config/**,**/*Application.java,**/model/**,**/repository/**,**/dto/**
